# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: luther007/cynerge-pipeline-test # ADD YOUR DOCKER HUB REPO HERE
  tag: latest
  pullPolicy: Always

env:
hpa:
  minReplicas: 1
  maxReplicas: 3

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: puppet-pipeline-test
  type: LoadBalancer
  externalPort: 8080
  internalPort: 8080
  # annotations:
  #   fabric8.io/expose: "true"
  #   fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 800Mi

# probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
